plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/umei/Library/Mobile Documents/com~apple~CloudDocs/AIMei/AIDesign Lab/IIB_Token_Viewer"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]